### ISSUE TITLE
Code Review By Zak

### ISSUE THREAD

**Issue by zakkariyaa** [fac28/DoggyDB#53]
First i want to start by saying well done! You have accomplished a lot in a short time and the site looks amazing, especially the styling. Here are few minor things that popped out to me:

- Responsiveness: The site looks good on bigger screens but is not fully responsive
- When you click on the "breed" button to filter by breed, you get "Internal server error"
- I couldn't understand what the "Join the club" functionality does, and i couldn't find anything on that in the README
- That connects to my next point: the README was very minimal info

But as i said, minor stuff. Few things i liked:

- The filtering functionality and how the filter button' styling gets updated when you click
- The CSS: very clear and very visually appealing
- and of course the dog in the background :)

**Comment by yuqingwwang** [comment]
- [x]  breed should not be null (what's currently preventing sorting)
- [x]  join the club button will be removed
- [x]  readme expanded
